version: '3'

services:

  mongodb:
    container_name: mongodb
    image: mongo:latest
    volumes:
      - db_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend
    restart: always

volumes:
  db_data:
    driver: local

networks:
  backend:
